version: "3"

services:
  web:
    image: node:13.8.0-alpine3.10
    volumes:
      - .:/docz
    ports:
      - "8889:9000"
    working_dir: /docz
    entrypoint:
      - npm
      - run
      - docz:serve
